export const varToScreenEngine = {
    // identification
    identification: "Identification",
    engineID: "Engine ID",
    manufacturer: "Manufacturer",
    make: "Make",
    model: "Model",
    year: "Year",
    serialNumber: "Serial Number",
  
    // basics
    basics: "Basics",
    engineType: "Engine Type",
    horsepower: "Horsepower",
    torque: "Torque",
    rpmRange: "RPM Range",
    weight: "Weight",
    displacement: "Displacement",
    compressionRatio: "Compression Ratio",
  
    // generalDetails
    generalDetails: "General Details",
    engineBlockMaterial: "Engine Block Material",
    engineMountingType: "Engine Mounting Type",
    cylinderConfiguration: "Cylinder Configuration",
    numberOfCylinders: "Number of Cylinders",
    valvesPerCylinder: "Valves Per Cylinder",
    boreAndStroke: "Bore and Stroke",
    fuelSystem: "Fuel System",
    ignitionSystem: "Ignition System",
    coolingSystem: "Cooling System",
    exhaustSystem: "Exhaust System",
  
    // fuelAndEmissions
    fuelAndEmissions: "Fuel and Emissions",
    fuelType: "Fuel Type",
    fuelConsumption: "Fuel Consumption",
    fuelTankCapacity: "Fuel Tank Capacity",
    emissionStandards: "Emission Standards",
    co2Emissions: "CO2 Emissions",
    noxEmissions: "NOx Emissions",
    exhaustAftertreatment: "Exhaust Aftertreatment",
  
    // performanceAndHandling
    performanceAndHandling: "Performance and Handling",
    maxPowerOutput: "Max Power Output",
    continuousPower: "Continuous Power",
    operatingRPM: "Operating RPM",
    fuelEfficiency: "Fuel Efficiency",
    engineSpeedControl: "Engine Speed Control",
  
    // serviceAndMaintenance
    serviceAndMaintenance: "Service and Maintenance",
    maintenanceInterval: "Maintenance Interval",
    maintenanceSchedule: "Maintenance Schedule",
    oilType: "Oil Type",
    oilCapacity: "Oil Capacity",
    oilFilterType: "Oil Filter Type",
    oilChangeInterval: "Oil Change Interval",
    coolingSystemCapacity: "Cooling System Capacity",
    sparePartsAvailability: "Spare Parts Availability",
  
    // transmissionAndDrive
    transmissionAndDrive: "Transmission and Drive",
    transmissionType: "Transmission Type",
    gearRatio: "Gear Ratio",
    propulsionSystem: "Propulsion System",
    driveType: "Drive Type",
    gearbox: "Gearbox",
    propellerType: "Propeller Type",
    shaftLength: "Shaft Length",
  
    // electricalAndControlSystems
    electricalAndControlSystems: "Electrical and Control Systems",
    alternatorOutput: "Alternator Output",
    batteryType: "Battery Type",
    batteryVoltage: "Battery Voltage",
    engineControlUnit: "Engine Control Unit",
    starterMotor: "Starter Motor",
    sensors: "Sensors",
    monitoringSystems: "Monitoring Systems",
  
    // dimensionsAndWeight
    dimensionsAndWeight: "Dimensions and Weight",
    length: "Length",
    width: "Width",
    height: "Height",
    dryWeight: "Dry Weight",
    wetWeight: "Wet Weight",
  
    // accessoriesAndOptions
    accessoriesAndOptions: "Accessories and Options",
    soundproofingKits: "Soundproofing Kits",
    remoteControl: "Remote Control",
    engineHeater: "Engine Heater",
    vibrationIsolation: "Vibration Isolation",
    turbocharger: "Turbocharger",
    airIntakeFilter: "Air Intake Filter",
    powerTakeOff: "Power Take-Off",
  
    // safetyFeatures
    safetyFeatures: "Safety Features",
    emergencyStop: "Emergency Stop",
    overheatProtection: "Overheat Protection",
    lowOilPressureWarning: "Low Oil Pressure Warning",
    fireSuppressionSystem: "Fire Suppression System",
  
    // environmentalFeatures
    environmentalFeatures: "Environmental Features",
    ecoMode: "Eco Mode",
    lowEmissions: "Low Emissions",
    noiseLevel: "Noise Level",
    fuelEfficiencyRating: "Fuel Efficiency Rating",
  
    // regulatoryCompliance
    regulatoryCompliance: "Regulatory Compliance",
    epaCompliance: "EPA Compliance",
    euStageCompliance: "EU Stage Compliance",
    imoCompliance: "IMO Compliance",
    isoCertification: "ISO Certification",
  
    // paymentTerms
    paymentTerms: "Payment Terms",
    currency: "Currency",
    preferredPaymentMethod: "Preferred Payment Method",
    invoiceAndReceiptProcedures: "Invoice and Receipt Procedures",
    priceLabel: "Price Label",
    priceDrop: "Price Drop",
    vat: "VAT",
    totalPrice: "Total Price",
    globalAddressLookup: "Global Address Lookup",
    distance: "Distance",
    contactDetails: "Contact Details",
  };  

export const varToDb = {
    //Engine Details
    MarisailVesselID: "Marisail_Vessel_ID",
    EngineMake: "Engine_Make",
    EngineModel: "Engine_Model",
    EngineModelYear: "Engine_Model_Year",
    EngineType: "Engine_Type",
    TypeDesignation: "Type_Designation",

    // Condition
    Condition: "Condition",
    UsedCondition: "Used_Condition",
    Seller: "Seller",
    OfferedBy: "Offered_By",
    LastSurveyDate: "Last_Survey_Date",
    BrokerValuation: "Broker_Valuation",

    // General
    EngineClassifiable: "Engine_Classifiable",
    Certification: "Certification",
    ManufacturerWarranty: "Manufacturer_Warranty",
    EngineSerialNumber: "Engine_Serial_Number",
    CECategory: "CE_Category",
    NumberDrives: "Number_Drives",
    NumberEngines: "Number_Engines",
    Range: "Range",
    CruiseSpeed: "Cruise_Speed",
    DriveType: "Drive_Type",
    EngineHours: "Engine_Hours",
    IgnitionSystem: "Ignition_System",
    NoiseLevelDB: "Noise_Level_(dB)",
    EngineSoundproofingKits: "Engine_Soundproofing_Kits",

    // Transmission
    TransmissionType: "Transmission_Type",
    GearShift: "Gear_Shift",
    GearRatio: "Gear_Ratio",
    GearShiftType: "Gear_Shift_Type",
    FlywheelSAE: "Flywheel_SAE",
    FlywheelHousing: "Flywheel_Housing",
    Camshaft: "Camshaft",
    CrankshaftAlloy: "Crankshaft_Alloy",
    CrankcaseDesign: "Crankcase_Design",

    // Installation and Mounting
    InstallationAndMounting: "Installation_and_Mounting",
    EngineMountingOrientation: "Engine_Mounting_Orientation",
    EngineSuspension: "Engine_Suspension",
    EngineMountingType: "Engine_Mounting_Type",
    MountingBracketMaterial: "Mounting_Bracket_Material",
    AlignmentRequirements: "Alignment_Requirements",
    EngineBlock: "Engine_Block",

    // Service & Maintenance
    Maintenance: "Maintenance",
    ScheduledMaintenancePlan: "Scheduled_Maintenance_Plan",
    ServiceInterval: "Service_Interval",
    MaintenanceLogRequirements: "Maintenance_Log_Requirements",
    AvailabilityOfSpareParts: "Availability_of_Spare_Parts",
    OperationMode: "Operation_Mode",
    LastServiceDate: "Last_Service_Date",

    // Equipment
    EMS: "EMS",
    EngineControlSystem: "Engine_Control_System",
    UnitInjectors: "Unit_Injectors",
    Turbocharger: "Turbocharger",
    Turbocharging: "Turbocharging",
    StarterMotor: "Starter_Motor",
    ProtectionCovers: "Protection_Covers",
    CrankcaseVentilation: "Crankcase_Ventilation",
    HeatExchanger: "Heat_Exchanger",
    HeatExchangerWET: "Heat_Exchanger_WET",
    SeaWaterPump: "Sea_Water_Pump",
    ChargeAirCooler: "Charge_Air_Cooler",
    WorkingPrinciple: "Working_Principle",
    CompressionRatio: "Compression_Ratio",
    PistonSpeed1500: "Piston_Speed_1500",
    PistonSpeed1800: "Piston_Speed_1800",
    FiringOrder: "Firing_Order",
    Pistons: "Pistons",
    ConnectionRods: "Connection_Rods",
    AuxiliaryPTO: "Auxiliary_Power_Take-Off_(PTO)",
    RemoteControlSystems: "Remote_Control_Systems",

    // Dimensions
    Displacement: "Displacement",
    Length: "Length",
    Width: "Width",
    Height: "Height",
    EngineLength: "Engine_Length",
    EngineWeight: "Engine_Weight",
    DryWeight: "Dry_Weight",
    WeightExclOil: "Weight_Excl_Oil",
    WeightHeatExchanger: "Weight_Heat_Exchanger",
    WeighKeelCooling: "Weigh_Keel_Cooling",

    // Performance
    NominalRating: "Nominal_Rating",
    EnginePerformance: "Engine_Performance",
    MaxPowerOutput: "Max_Power_Output",
    MaxPower: "Max._Power",
    MaximumSpeed: "Maximum_Speed",
    Supercharged: "Supercharged",
    ValveTrain: "Valve_Train",
    GPFullLoadKw: "GP_Full_Load_Kw",
    GPFullLoadMetric: "GP_Full_Load_Metric",
    GPPropellerCurveKw: "GP_Propeller_Curve_Kw",
    GPPropellerCurveMetric: "GP_Propeller_Curve_Metric",
    GrossTorque: "Gross_Torque",
    ContinuousPower: "Continuous_Power_(kW/HP)",
    MaximumContinuousRating: "Maximum_Continuous_Rating_(MCR)",
    EngineSpeedRangeRPM: "Engine_Speed_Range_(RPM)",
    EngineEfficiency: "Engine_Efficiency",
    PowerToWeightRatio: "Power-to-Weight_Ratio",

    // Cylinders
    CylinderConfiguration: "Cylinder_Configuration",
    NumberCylinders: "Number_Cylinders",
    CylindersArrangement: "Cylinders_Arrangement",
    NumberValves: "Number_Valves",
    ValvePerCylinder: "Valve_per_Cylinder",
    BoreStroke: "Bore_Stroke",
    Bore: "Bore",

    // RPM
    IdleRPM: "Idle_RPM",
    RatedSpeed: "Rated_Speed",
    RPMAtMaxPower: "RPM_at_Max_Power",

    // Torque
    MaximumTorque: "Maximum_Torque",
    MaximumTorqueRPM: "Maximum_Torque_RPM",
    TorqueAtRatedSpeed: "Torque_At_Rated_Speed",

    // Cooling System 
    Aftercooled: "Aftercooled",
    CoolingSystem: "Cooling_System",
    ClosedCoolingSystem: "Closed_Cooling_System",
    OpenCoolingSystem: "Open_Cooling_System",
    Intercooled: "Intercooled",
    RecommendedCoolant: "Recommended_Coolant",
    CoolingType: "Cooling_Type",
    HeatExchangerMaterial: "Heat_Exchanger_Material",
    HeatDissipationRate: "Heat_Dissipation_Rate",
    EngineLubrication: "Engine_Lubrication",
    LubricationSystem: "Lubrication_System",
    CoolingCapacity: "Cooling_Capacity_(L/min)",
    CoolingFluidType: "Cooling_Fluid_Type",
    CoolingSystemPressure: "Cooling_System_Pressure",
    AirFilterType: "Air_Filter_Type",
    CirculationPumpType: "Circulation_Pump_Type",
    RawWaterPumpType: "Raw_Water_Pump_Type",

    // Propulsion System
    Propulsion: "Propulsion",
    Bowthruster: "Bowthruster",
    PropulsionSystem: "Propulsion_System",
    PropulsionSystemType: "Propulsion_System_Type",
    PropellerDiameter: "Propeller_Diameter",
    PropellerMaterial: "Propeller_Material",
    PropellerPitch: "Propeller_Pitch",
    PropellerType: "Propeller_Type",
    PropellerShaftDiameter: "Propeller_Shaft_Diameter",
    GearboxType: "Gearbox_Type",
    TransmissionCooling: "Transmission_Cooling",
    PropellerBladeMaterial: "Propeller_Blade_Material",
    PropellerShaftMaterial: "Propeller_Shaft_Material",
    SteeringSystem: "Steering_System",
    SteeringControlType: "Steering_Control_Type",
    TrimSystem: "Trim_System",
    TrimTabMaterial: "Trim_Tab_Material",
    TrimTabType: "Trim_Tab_Type",

    // Fuel System 
    EFI: "EFI",
    FuelPreFilter: "Fuel_Pre-Filter",
    FuelFilter: "Fuel_Filter",
    FuelFilterType: "Fuel_Filter_Type",
    FuelReserve: "Fuel_Reserve",
    FuelSystem: "Fuel_System",
    FuelTankCapacity: "Fuel_Tank_Capacity",
    FuelType: "Fuel_Type",
    LowestFuelConsumption: "Lowest_Fuel_Consumption",
    RecommendedFuel: "Recommended_Fuel",
    FuelReserve: "Fuel_Reserve",
    FuelConsumptionRate: "Fuel_Consumption_Rate",
    FCFullLoad: "FC_Full_Load",
    FuelInjectionSystemType: "Fuel_Injection_System_Type",
    FuelDeliveryPressure: "Fuel_Delivery_Pressure",
    FuelTankMaterial: "Fuel_Tank_Material",
    FuelLineDiameter: "Fuel_Line_Diameter",

    // Fuel Consumption
    FC34Load: "FC_3/4_Load",
    FC12Load: "FC_1/2_Load",
    FCPropellerCurve: "FC_Propeller_Curve",
    HeatRejection: "Heat_Rejection",

    // Oil
    OilFilter: "Oil_Filter",
    OilFilterType: "Oil_Filter_Type",
    CentrifugalOilCleaner: "Centrifugal_Oil_Cleaner",
    OilCooler: "Oil_Cooler",
    OilFiller: "Oil_Filler",
    OilDipstick: "Oil_Dipstick",
    RecommendedOil: "Recommended_Oil",
    OilCapacity: "Oil_Capacity",
    OilChangeInterval: "Oil_Change_Interval",
    OilCoolingMethod: "Oil_Cooling_Method",
    LubricationOilPressure: "Lubrication_Oil_Pressure",
    OilFilterBypassValve: "Oil_Filter_Bypass_Valve",

    // Electrical System
    Alternator: "Alternator",
    AlternatorOutput: "Alternator_Output",
    BatteryType: "Battery_Type",
    BatteryVoltage: "Battery_Voltage",
    AlternatorOutputAmps: "Alternator_Output_(Amps)",
    StarterMotorVoltage: "Starter_Motor_Voltage",
    EngineControlUnitECUModel: "Engine_Control_Unit_(ECU)_Model",
    BatteryChargingSystem: "Battery_Charging_System",
    IntegratedGenerator: "Integrated_Generator",

    // Emmissions & Environment
    EmissionCompliance: "Emission_Compliance",
    ExhaustSystem: "Exhaust_System",
    ExhaustSystemType: "Exhaust_System_Type",
    ExhaustGasAfterTreatment: "Exhaust_Gas_After_Treatment",
    ExhaustGasStatus: "Exhaust_Gas_Status",
    ExhaustValveTiming: "Exhaust_Valve_Timing",
    IntakeValveTiming: "Intake_Valve_Timing",
    EmissionControlTechnology: "Emission_Control_Technology",
    NOxEmissions: "NOx_Emissions_(g/kWh)",
    SOxEmissions: "SOx_Emissions_(g/kWh)",
    CO2Emissions: "CO2_Emissions_(g/kWh)",
    ComplianceWithIMOTierStandards: "Compliance_with_International_Maritime_Organization_(IMO)_Tier_Standards",

    // Safety and Monitoring
    SafetyAndMonitoring: "Safety_and_Monitoring",
    EngineMonitoringSystems: "Engine_Monitoring_Systems",
    OverheatProtection: "Overheat_Protection",
    LowOilPressureAlarm: "Low_Oil_Pressure_Alarm",
    EmergencyStopSystem: "Emergency_Stop_System",
    AutomaticUpdates: "Automatic_Updates",

    // Payment Terms
    PaymentTerms: "Payment_Terms",
    Currency: "Currency",
    PreferredPayment: "Preferred_Payment",
    InvoiceReceipt: "Invoice_Receipt",
    CalculatePriceAndPay: "Calculate",
    PriceLabel: "Price_Label",
    PriceDrop: "Price_Drop"
};

export const detailStateType = {
    engineIdentification: {
      marisailVesselID: "",
      engineMake: "",
      engineModel: "",
      engineModelYear: "",
      engineType: "",
      typeDesignation: "",
    },
    condition: {
      usedCondition: "",
      seller: "",
      offeredBy: "",
      lastSurveyDate: "",
      brokerValuation: "",
    },
    generalDetails: {
      engineClassification: "",
      certification: "",
      manufacturerWarranty: "",
      engineSerialNumber: "",
      ceDesignCategory: "",
      numberDrives: "",
      numberEngines: "",
      rangeMiles: "",
      cruisingSpeedKnots: "",
      driveType: "",
      engineHours: "",
      ignitionSystem: "",
      noiseLevel: "",
      engineSoundproofingKits: "",
    },
    transmission: {
      transmissionType: "",
      gearShift: "",
      gearRatio: "",
      gearShiftType: "",
      flywheelSAE: "",
      flywheelHousing: "",
      camshaft: "",
      crankshaftAlloy: "",
      crankcaseDesign: "",
    },
    installationAndMounting: {
      engineMountingOrientation: "",
      engineSuspension: "",
      engineMountingType: "",
      mountingBracketMaterial: "",
      alignmentRequirements: "",
      engineBlock: "",
    },
    serviceAndMaintenance: {
      scheduledMaintenancePlan: "",
      serviceInterval: "",
      maintenanceLogRequirements: "",
      availabilityOfSpareParts: "",
      operationMode: "",
      lastServiceDate: "",
    },
    equipment: {
      engineManagementSystem: "",
      engineControlSystem: "",
      unitInjectors: "",
      turbocharger: "",
      turbocharging: "",
      starterMotor: "",
      protectionCovers: "",
      closedCrankcaseVentilation: "",
      heatExchanger: "",
      heatExchangerWithExpansionTank: "",
      seaWaterPump: "",
      seaWaterCooledChargeAirCooler: "",
      workingPrinciple: "",
      compressionRatio: "",
      pistonSpeed1500Rpm: "",
      pistonSpeed1800Rpm: "",
      firingOrder: "",
      pistons: "",
      connectionRods: "",
      auxiliaryPowerTakeOff: "",
      remoteControlSystems: "",
    },
    dimensions: {
      displacement: "",
      length: "",
      width: "",
      height: "",
      lengthFromFrontEndToFlywheelHousing: "",
      engineWeight: "",
      dryWeight: "",
      weightExclOilAndCoolant: "",
      weightWithHeatExchanger: "",
      weightWithKeelCooling: "",
    },
    performance: {
      nominalRating: "",
      enginePerformance: "",
      maxPowerOutput: "",
      maxPower: "",
      maxSpeed: "",
      supercharged: "",
      valveTrain: "",
      grossPowerFullLoadKw: "",
      grossPowerFullLoadHpMetric: "",
      grossPowerPropellerCurveKw: "",
      grossPowerPropellerCurveHpMetric: "",
      grossTorqueNm: "",
      continuousPowerKwHP: "",
      maximumContinuousRatingMCR: "",
      engineSpeedRangeRPM: "",
      engineEfficiency: "",
      powerToWeightRatio: "",
    },
    cylinders: {
      cylinderConfiguration: "",
      numberCylinders: "",
      cylindersAndArrangement: "",
      numberValves: "",
      valvePerCylinder: "",
      boreXStroke: "",
      bore: "",
      stroke: "",
    },
    rpm: {
      idleRPM: "",
      ratedSpeed: "",
      rpmAtMaxPower: "",
    },
    torque: {
      maximumTorqueNm: "",
      maximumTorqueAtSpeedRPM: "",
      torqueAtRatedSpeedNm: "",
    },
    coolingSystem: {
      aftercooled: "",
      coolingSystem: "",
      closedCoolingSystem: "",
      openCoolingSystem: "",
      intercooled: "",
      recommendedCoolant: "",
      coolingType: "",
      heatExchangerMaterial: "",
      heatDissipationRate: "",
      engineLubrication: "",
      lubricationSystem: "",
      coolingCapacityLmin: "",
      coolingFluidType: "",
      coolingSystemPressure: "",
      airFilterType: "",
      circulationPumpType: "",
      rawWaterPumpType: "",
    },
    propulsionSystem: {
      propulsion: "",
      bowthruster: "",
      propulsionSystem: "",
      propulsionSystemType: "",
      propellerDiameter: "",
      propellerMaterial: "",
      propellerPitch: "",
      propellerType: "",
      propellerShaftDiameter: "",
      gearboxType: "",
      transmissionCooling: "",
      propellerBladeMaterial: "",
      propellerShaftMaterial: "",
      steeringSystem: "",
      steeringControlType: "",
      trimSystem: "",
      trimTabMaterial: "",
      trimTabType: "",
    },
    fuelSystem: {
      electronicFuelInjection: "",
      fuelPreFilter: "",
      fuelFilter: "",
      fuelFilterType: "",
      fuelReserveLitres: "",
      fuelSystem: "",
      fuelTankCapacityLitres: "",
      fuelType: "",
      lowestSpecificFuelConsumption: "",
      recommendedFuel: "",
      fuelConsumptionAtCruisingSpeedLitres: "",
      fuelConsumptionRate: "",
      fuelConsumptionAtFullLoadGkwh: "",
      fuelInjectionSystemType: "",
      fuelDeliveryPressure: "",
      fuelTankMaterial: "",
      fuelLineDiameter: "",
    },
    fuelConsumption: {
      fuelConsumptionAt34LoadGkwh: "",
      fuelConsumptionAt12LoadGkwh: "",
      fuelConsumptionPropellerCurveLH: "",
      heatRejectionToCoolantKw: "",
    },
    oilSystem: {
      oilFilter: "",
      oilFilterType: "",
      centrifugalOilCleaner: "",
      oilCooler: "",
      oilFiller: "",
      oilDipstick: "",
      recommendedOil: "",
      oilCapacity: "",
      oilChangeInterval: "",
      oilCoolingMethod: "",
      lubricationOilPressure: "",
      oilFilterBypassValve: "",
    },
    electricalSystem: {
      alternator: "",
      alternatorOutput: "",
      batteryType: "",
      batteryVoltage: "",
      generatorOutputKw: "",
      alternatorOutputAmps: "",
      starterMotorVoltage: "",
      engineControlUnitModel: "",
      batteryChargingSystem: "",
      integratedGenerator: "",
    },
    emissionsAndEnvironment: {
      emissionCompliance: "",
      exhaustSystem: "",
      exhaustSystemType: "",
      exhaustGasAfterTreatment: "",
      exhaustGasStatus: "",
      exhaustValveTiming: "",
      intakeValveTiming: "",
      emissionControlTechnology: "",
      noxEmissionsGkwh: "",
      soxEmissionsGkwh: "",
      co2EmissionsGkwh: "",
      complianceWithIMOStandards: "",
    },
    safetyAndMonitoring: {
      engineMonitoringSystems: "",
      overheatProtection: "",
      lowOilPressureAlarm: "",
      emergencyStopSystem: "",
    },
    paymentTerms: {
      paymentTerms: "",
      currency: "",
      preferredPaymentMethod: "",
      invoiceAndReceiptProcedures: "",
      priceLabel: "",
      priceDrop: "",
      vat: "",
    },
  };
  

export const typeDef = {
    identification: {
      marisailEngineId: [],
      manufacturer: [],
      make: [],
      model: [],
      year: [],
      serialNumber: [],
    },
    basics: {
      engineType: [],
      horsepower: [],
      torque: [],
      rpmRange: [],
      weight: [],
      displacement: [],
      compressionRatio: [],
    },
    generalDetails: {
      engineBlockMaterial: [],
      engineMountingType: [],
      cylinderConfiguration: [],
      numberOfCylinders: [],
      valvesPerCylinder: [],
      boreAndStroke: [],
      fuelSystem: [],
      ignitionSystem: [],
      coolingSystem: [],
      exhaustSystem: [],
    },
    fuelAndEmissions: {
      fuelType: [],
      fuelConsumption: [],
      fuelTankCapacity: [],
      emissionStandards: [],
      co2Emissions: [],
      noxEmissions: [],
      exhaustAftertreatment: [],
    },
    performanceAndHandling: {
      maxPowerOutput: [],
      continuousPower: [],
      operatingRPM: [],
      fuelEfficiency: [],
      engineSpeedControl: [],
    },
    serviceAndMaintenance: {
      maintenanceInterval: [],
      maintenanceSchedule: [],
      oilType: [],
      oilCapacity: [],
      oilFilterType: [],
      oilChangeInterval: [],
      coolingSystemCapacity: [],
      sparePartsAvailability: [],
    },
    transmissionAndDrive: {
      transmissionType: [],
      gearRatio: [],
      propulsionSystem: [],
      driveType: [],
      gearbox: [],
      propellerType: [],
      shaftLength: [],
    },
    electricalAndControlSystems: {
      alternatorOutput: [],
      batteryType: [],
      batteryVoltage: [],
      engineControlUnit: [],
      starterMotor: [],
      sensors: [],
      monitoringSystems: [],
    },
    dimensionsAndWeight: {
      length: [],
      width: [],
      height: [],
      dryWeight: [],
      wetWeight: [],
    },
    accessoriesAndOptions: {
      soundproofingKits: [],
      remoteControl: [],
      engineHeater: [],
      vibrationIsolation: [],
      turbocharger: [],
      airIntakeFilter: [],
      powerTakeOff: [],
    },
    safetyFeatures: {
      emergencyStop: [],
      overheatProtection: [],
      lowOilPressureWarning: [],
      fireSuppressionSystem: [],
    },
    environmentalFeatures: {
      ecoMode: [],
      lowEmissions: [],
      noiseLevel: [],
      fuelEfficiencyRating: [],
    },
    regulatoryCompliance: {
      epaCompliance: [],
      euStageCompliance: [],
      imoCompliance: [],
      isoCertification: [],
    },
    paymentTerms: {
      paymentTerms: [],
      currency: [],
      preferredPaymentMethod: [],
      invoiceAndReceiptProcedures: [],
      priceLabel: [],
      vat: [],
      totalPrice: [],
      globalAddressLookup: [],
      contactDetails: [],
    },
  };
  

export const makeString = (str) => {
    var newStr = "";
    newStr += str[0].toUpperCase();
    for (let i = 1; i < str.length; i++) {
      if (str[i] === str[i].toUpperCase() || i === 0) {
        newStr += " " + str[i];
      } else {
        newStr += str[i];
      }
    }
  
    // ID, VAT, EU wagera ka hisab dekhna h
  
    // console.log(newStr);
    return newStr;
  };