// src/config/Transport_Config.js

export const Transport_Config = {
  schema_name: "Transport",
  main_table: "Job",
  primary_key: "Transport_Item_ID",
  join_tables: [
    "Compliance",
    "Haulage",
    "Haulier",
    "Questions",
    "Reviews",
    "Transportation_Contacts",
    "Transportation_Payment",
    "Transportation_Quotes",
    "Transportation_Sales",
  ],
  tables: [
    {
      table_Name: "Job",
      section_Heading: "Job Description",
      columns: {
        transport_Id: {
          column_Name: "Transport_Item_ID",
          displayText: "Transport Item ID",
          type: "radio",
          mandatory: false,
          searchable: true,
          radioOptions: null,
        },
        category: {
          column_Name: "Category",
          displayText: "Category",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: null,
        },
        title: {
          column_Name: "Title",
          displayText: "Title",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: null,
        },
        description: {
          column_Name: "Description",
          displayText: "Description",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: null,
        },
        deadlineDate: {
          column_Name: "Deadline_Date",
          displayText: "Deadline Date",
          type: "date",
          mandatory: true,
          searchable: true,
          radioOptions: null,
        },
        timescale: {
          column_Name: "Timescale",
          displayText: "Timescale",
          type: "date",
          mandatory: true,
          searchable: true,
          radioOptions: null,
        },
        preferredDate: {
          column_Name: "Preferred_Date",
          displayText: "Preferred Date",
          type: "date",
          mandatory: true,
          searchable: true,
          radioOptions: null,
        },
        international: {
          column_Name: "International",
          displayText: "International",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: ["Yes", "No"],
        },
        ferryRequired: {
          column_Name: "Ferry_Required",
          displayText: "Ferry Required",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: ["Yes", "No"],
        },
        specialHandlingRequirements: {
          column_Name: "Special_Handling",
          displayText: "Special Handling",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: null,
        },
        departureLoadingEquipmentNeeded: {
          column_Name: "Loading_Equipment",
          displayText: "Loading Equipment Required?",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: ["Yes", "No"],
        },
        destinationUnloadingEquipmentNeeded: {
          column_Name: "Unloading_Equipment",
          displayText: "Unloading Equipment Required?",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: ["Yes", "No"],
        },
        overweightPermitNeeded: {
          column_Name: "Overweight_Permit",
          displayText: "Overweight Permit Required?",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: ["Yes", "No"],
        },
        oversizePermitNeeded: {
          column_Name: "Oversize_Permit",
          displayText: "Oversize Permit Required",
          type: "radio",
          mandatory: true,
          searchable: true,
          radioOptions: ["Yes", "No"],
        },
        postedDate: {
          column_Name: "Posted_Date",
          displayText: "Posted Date",
          type: "date",
          mandatory: false,
          searchable: true,
          radioOptions: null,
        },
        haulierToDepartureDistance: {
          column_Name: "Collection_Delivery_Distance",
          displayText: "Collection Delivery Distance",
          type: "radio",
          mandatory: false,
          searchable: true,
          radioOptions: null,
        },
        departureToDestinationDistance: {
          column_Name: "Departure_Destination",
          displayText: "Departure Destination",
          type: "radio",
          mandatory: false,
          searchable: true,
          radioOptions: null,
        },
        returnJourney: {
          column_Name: "Return_Journey",
          displayText: "Return Journey",
          type: "radio",
          mandatory: false,
          searchable: true,
          radioOptions: ["Yes", "No"],
        },
        roundTripDistance: {
          column_Name: "Round_Trip_Distance",
          displayText: "Round Trip Distance",
          type: "radio",
          mandatory: false,
          searchable: true,
          radioOptions: null,
        },
        freightClass: {
          column_Name: "Freight_Class",
          displayText: "Freight Class",
          type: "radio",
          mandatory: false,
          searchable: true,
          radioOptions: null,
        },
        numberQuotes: {
          column_Name: "Number_Quotes",
          displayText: "Number Quotes",
          type: "number",
          mandatory: false,
          searchable: true,
          radioOptions: null,
        },
        jobDoneHaulier: {
          column_Name: "Job_Done_Haulier",
          displayText: "Job Done Date",
          type: "radio",
          mandatory: false,
          searchable: true,
          radioOptions: null,
        },
        jobDoneDate: {
          column_Name: "Job_Done_Date_Haulier",
          displayText: "Job Done Date",
          type: "date",
          mandatory: false,
          searchable: true,
          radioOptions: null,
        },
      },
    },
    // (Include other tables like Vessel_Details, Transportation_Contacts, etc. here, omitted for brevity)
  ],
};

// Now export the helper maps used in your router

// Map variable keys used in frontend or API filter to DB column names
export const transportVarToColumn = {
  category: "Category",
  title: "Title",
  description: "Description",
  deadlineDate: "Deadline_Date",
  timescale: "Timescale",
  preferredDate: "Preferred_Date",
  international: "International",
  ferryRequired: "Ferry_Required",
  specialHandlingRequirements: "Special_Handling",
  departureLoadingEquipmentNeeded: "Loading_Equipment",
  destinationUnloadingEquipmentNeeded: "Unloading_Equipment",
  overweightPermitNeeded: "Overweight_Permit",
  oversizePermitNeeded: "Oversize_Permit",
  postedDate: "Posted_Date",
  haulierToDepartureDistance: "Collection_Delivery_Distance",
  departureToDestinationDistance: "Departure_Destination",
  returnJourney: "Return_Journey",
  roundTripDistance: "Round_Trip_Distance",
  freightClass: "Freight_Class",
  numberQuotes: "Number_Quotes",
  jobDoneHaulier: "Job_Done_Haulier",
  jobDoneDate: "Job_Done_Date_Haulier",
  // Add more as needed
};

// Map frontend table names to actual DB table names
export const transportVarToTable = {
  Job: "Job",
  Vessel_Details: "Vessel_Details",
  Transportation_Contacts: "Transportation_Contacts",
  Transportation_Quotes: "Transportation_Quotes",
  Questions: "Questions",
  Reviews: "Reviews",
  Haulier: "Haulier",
  Compliance: "Compliance",
  Transportation_Payment: "Transportation_Payment",
  Transportation_Sales: "Transportation_Sales",
  // Add more if needed
};

// List of tables to join when fetching detail by Transport_Item_ID
export const transportUniqueTable = [
  "Job",
  "Compliance",
  "Haulage",
  "Haulier",
  "Questions",
  "Reviews",
  "Transportation_Contacts",
  "Transportation_Payment",
  "Transportation_Quotes",
  "Transportation_Sales",
];

